<?php
echo'<ul>
<li>Bhaktapur</li>
<li>Biratnager</li>
<li>Birjung</li>
<li>Birtamod</li>
<li>Butwal</li>
<li>Chitwan</li>
<li>Dhangadhi</li>
<li>Dharan</li>
<li>Dhulikhal</li>
<li>Hetauda</li>
<li>Itahari</li>
<li>Janakpur</li>
<li>Kakarvitta</li>
<li>Kathamandu</li>
<li>Lalitpur</li>
<li>Lumbini</li>
<li>Nagarkot</li>
<li>Nepalgung</li>
<li>Pokhara</li>
<li>Namchabazzar</li>
<li>Dolpa</li>
</ul>
</ul>';
?>
